### PR TITLE
WIP Entity Presenters

### PR DESCRIPTION
**Pull request by ricog**
:construction: :construction: :construction:

This PR is for work and discussion on [Entity Presenters](https://github.com/cakephp/cakephp/issues/6698) and is not intended to be merged into the `loadsys/cakephp` repository. After completion a new PR will be opened on `cakephp/cakephp`
with a more appropriate merge target.

### CODE REVIEW

**Comment by ricog** [comment]
Will re-open a new PR with a merge target I can safely move around.

**Comment by alecho** [comment]
@ricog can you keep me updated on this? Maybe mention me in new PRs?

**Comment by ricog** [comment]
Will Do. Thanks for your help so far on this @alecho .

**Comment by beporter** [comment]
Just thought about something. We should have a parallel PR ready to submit at the same time as the code for the book updates. If this is going to be a core feature, then it can't get merged without it being explained. The same goes for the core skeleton, if there are going to be new folders and paths for Presenter classes.

**Comment by ricog** [comment]
Good point. I created 2 issues to cover these cases. #11 and #12

**Pull request closed without merging**
